// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxSc6e1sqrud9Fmmsi_7d_Da0HmBWVVG8',
    appId: '1:705235437995:web:9002b506a4b75b28f52aee',
    messagingSenderId: '705235437995',
    projectId: 'vitalise02',
    authDomain: 'vitalise02.firebaseapp.com',
    storageBucket: 'vitalise02.appspot.com',
    measurementId: 'G-XZDVY6JKDJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN3Je0yg1XRWHn_QR384GA6Cx-wpL4p5g',
    appId: '1:705235437995:android:f2cd141cf78c5488f52aee',
    messagingSenderId: '705235437995',
    projectId: 'vitalise02',
    storageBucket: 'vitalise02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXxbte6sIiy4LY-8f5eYCY5Z20YT7nxxM',
    appId: '1:705235437995:ios:2a17faaaa6336147f52aee',
    messagingSenderId: '705235437995',
    projectId: 'vitalise02',
    storageBucket: 'vitalise02.appspot.com',
    iosBundleId: 'com.example.vitalize',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXxbte6sIiy4LY-8f5eYCY5Z20YT7nxxM',
    appId: '1:705235437995:ios:bda40ced75e936c2f52aee',
    messagingSenderId: '705235437995',
    projectId: 'vitalise02',
    storageBucket: 'vitalise02.appspot.com',
    iosBundleId: 'com.example.vitalize.RunnerTests',
  );
}
